apiVersion: v1
kind: Pod
metadata: 
   name: lychee-example
   labels:
     app: lychee 
spec:
   containers:
     - name: lychee
       image: linuxserver/lychee:version-v4.2.2 
       ports:
         - containerPort: 80
           name: "lychee-http"


---
apiVersion: v1
kind: Service
metadata:
     name: lychee-example
spec:
     type: NodePort
     ports:
       - name: http
         port: 80
         nodePort: 30180
         targetPort: lychee-http
     selector:
       app: lychee 

